version: '3.8'

services:
  db:
    image: postgres:15
    container_name: neodanneo_db
    environment:
      POSTGRES_USER: danneo
      POSTGRES_PASSWORD: password
      POSTGRES_DB: neodanneo
    ports:
      - "5432:5432"
    volumes:
      - pg_data_2:/var/lib/postgresql/data

  minio:
    image: minio/minio
    container_name: neodanneo_storage
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

volumes:
  pg_data:
  pg_data_2:
  minio_data:
