[package]
name = "danneo-native-storage"
version = "2.0.0"
edition = "2024"

[dependencies]
danneo-sdk = { path = "../../danneo-sdk" }
sea-orm.workspace = true
serde.workspace = true
serde_json.workspace = true
async-trait.workspace = true
axum.workspace = true
tracing.workspace = true
rust-s3 = "0.37"
base64 = "0.21"
reqwest = { version = "0.12", features = ["json"] }
tokio.workspace = true

[dev-dependencies]
danneo-core = { path = "../../core" }
tokio = { workspace = true, features = ["full"] }
