[package]
id = "security"
name = "Access Control Management"
version = "2.0.0"
description = "Manage admins and groups"
type = "module"

[module]
runtime_type = "native"

[install]
default_enabled = true
